spring.application.name=product prices

server.servlet.context-path=/api

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.default-flat-paramObject=true

spring.datasource.url=jdbc:h2:mem:pricesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
mybatis.configuration.map-underscore-to-camel-case=true